Refactoring.

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -27,16 +27,15 @@ fail () {
   exit
 }
 
+
+
+
 setup_gitconfig () {
   if ! [ -f git/gitconfig.local.symlink ]
   then
     info 'setup gitconfig'
 
     git_credential='cache'
-    if [ "$(uname -s)" == "Darwin" ]
-    then
-      git_credential='osxkeychain'
-    fi
 
     user ' - What is your github author name?'
     read -e git_authorname
@@ -137,23 +136,32 @@ install_dotfiles () {
   done
 }
 
+install_dependencies () {
+  if [ "$(uname -s)" == "Linux" ]
+  then
+    info "installing dependencies"
+    if source bin/dotdot #| while read -r data; do echo "$data"; "$data"; done
+    then
+      success "dependencies installed"
+    else
+      fail "error installing dependencies"
+    fi
+  fi
+}
+
+append_to_bashrc () {
+  info "append 'source' line to .bashrc" 
+  echo "$DOTFILES_ROOT"
+  grep -q -F 'source "$HOME/.dotfiles/bash/dotfilesrc"' ~/.bashrc || echo 'source "$HOME/.dotfiles/bash/dotfilesrc"' >> ~/.bashrc
+
+}
+
 setup_gitconfig
 install_dotfiles
-
-# If we're on a Mac, let's install and setup homebrew.
-if [ "$(uname -s)" == "Linux" ]
-then
-  info "installing dependencies"
-  if source bin/dotdot #| while read -r data; do echo "$data"; "$data"; done
-  then
-    success "dependencies installed"
-  else
-    fail "error installing dependencies"
-  fi
-fi
+install_dependencies
+append_to_bashrc
 
 echo ''
 echo '  All installed!'
-
 
 
